const MOCK_DATA = [
    {
        id: 1,
        nombre: "Totem",
        descripcion: "lorem ipsum...",
        precio: 25,
        img: "./totemFake.svg"
    },
    {
        id: 2,
        nombre: "Espejo",
        descripcion: "lorem ipsum...",
        precio: 35,
        img: "./espejoFake.svg"
    },
    {
        id: 3,
        nombre: "Cupido",
        descripcion: "lorem ipsum...",
        precio: 50,
        img: "./cupidoFake.svg"
    },
    {
        id: 4,
        nombre: "Anillo",
        descripcion: "lorem ipsum...",
        precio: 75,
        img: "./anilloFake.svg"
    },
    {
        id: 5,
        nombre: "Abstraccion",
        descripcion: "lorem ipsum...",
        precio: 20,
        img: "./abstraccionFake.svg"
    },
]

export default MOCK_DATA